import './globals.css'
import { Inter } from 'next/font/google'
import Navbar from '@/components/Navbar'
import React from 'react'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
      
  <main className="">
         <Navbar/>
        
    <div className="flex col-span-4 min-h-screen flex-col items-center p-24">
        {children}
      </div>
      </main>
      </body>
    </html>
  )
}
